name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test test/Liftbridge.Net.UnitTests -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release -o assets --version-suffix alpha
    - name: Push
      run: dotnet nuget push .\assets\Liftbridge.Net.*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}